# Generated by Django 6.0.3 on 2026-03-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('Hostel', 'Hostel'), ('Academic', 'Academic'), ('Infrastructure', 'Infrastructure'), ('Technical', 'Technical'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
    ]
