# Generated by Django 6.0.3 on 2026-03-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_category_complaint_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
